import sbt._

/** The resources the compiler reads through `SourceFiles.readResource` (the standard library, the error
 *  explanations, the reference's URL) as a generated Scala object, for the browser build, which has no
 *  class path: `hugin.platform.BundledResources` (see the `js` project in `build.sbt`). */
object BundledResources {

  /** The resources: resource name (`/hugin/...`) and the file it comes from. */
  def inputs(base: File): Seq[(String, File)] = {
    val stdlib = base / "src" / "main" / "resources" / "hugin" / "stdlib"
    val std = (stdlib ** "*.hgn").get.sortBy(_.getPath).map(f => ("/hugin/stdlib/" + IO.relativize(stdlib, f).get.replace('\\', '/')) -> f)
    val errors = (base / "docs" / "errors" * "*.md").get.sortBy(_.getName).map(f => ("/hugin/errors/" + f.getName) -> f)
    std ++ errors :+ ("/hugin/site-url.txt" -> base / "reference" / "site-url.txt")
  }

  /** Writes the object to `out`. Texts are split into literals of at most `Chunk` characters, joined at
   *  run time, so that no constant exceeds the class file's limit of 65535 bytes. */
  def generate(base: File, out: File): File = {
    val entries = inputs(base).map { case (name, f) =>
      val chunks = IO.read(f, IO.utf8).grouped(Chunk).map(literal).mkString(",\n      ")
      s"    ${literal(name)} -> Array(\n      $chunks\n    )"
    }
    val code =
      s"""// Generated by project/BundledResources.scala from src/main/resources/hugin/stdlib, docs/errors and
         |// reference/site-url.txt; do not edit.
         |package hugin.platform
         |
         |private[platform] object BundledResources:
         |  def get(name: String): Option[String] = texts.get(name).map(_.mkString)
         |
         |  private val texts: Map[String, Array[String]] = Map(
         |${entries.mkString(",\n")}
         |  )
         |""".stripMargin
    IO.write(out, code, IO.utf8)
    out
  }

  private val Chunk = 8000

  private def literal(s: String): String = {
    val sb = new StringBuilder("\"")
    s.foreach {
      case '"' => sb ++= "\\\""
      case '\\' => sb ++= "\\\\"
      case '\n' => sb ++= "\\n"
      case '\r' => sb ++= "\\r"
      case '\t' => sb ++= "\\t"
      case c if c < ' ' || c > '~' => sb ++= "\\u%04x".format(c.toInt)
      case c => sb += c
    }
    (sb += '"').toString
  }
}
