package hugin.platform

import hugin.util.{Cancellation, SourceFiles}
import scala.scalajs.js

/** The browser's (and Node's) implementations of the compiler's platform interfaces, for the Scala.js build
 *  (the `js` project in `build.sbt`); the JVM's are in src/main/scala/hugin/platform. */
object Platform:
  /** No file system: the bundled resources only, so a program can import `std/` modules but no file. */
  val files: SourceFiles = JsSourceFiles

  /** The time (`Date.now()`, in milliseconds) after which an evaluation stops at its next round with the
   *  ordinary "evaluation cancelled", or infinity. The playground API sets it from a budget; a page that
   *  wants to stop a run at once terminates its worker instead. */
  var deadline: Double = Double.PositiveInfinity

  /** Whether the deadline has passed; once reported, the deadline is cleared. */
  val cancellation: Cancellation = () =>
    val over = js.Date.now() > deadline
    if over then deadline = Double.PositiveInfinity
    over

/** Bundled resources ([[BundledResources]], generated by the build) and POSIX path arithmetic on strings,
 *  following `java.nio.file.Path` on Unix: an invalid path (one with a NUL character) is reported by an
 *  `IllegalArgumentException`. */
private object JsSourceFiles extends SourceFiles:
  def readFile(path: String): Option[String] = None

  def readResource(name: String): Option[String] = BundledResources.get(name)

  def normalize(path: String): String =
    val absolute = valid(path).startsWith("/")
    val parts = scala.collection.mutable.ArrayBuffer.empty[String]
    for part <- path.split('/') if part.nonEmpty && part != "." do
      if part != ".." then parts += part
      else if parts.nonEmpty && parts.last != ".." then parts.remove(parts.length - 1)
      else if !absolute then parts += part
    (if absolute then "/" else "") + parts.mkString("/")

  def fileName(path: String): Option[String] =
    val trimmed = valid(path).reverse.dropWhile(_ == '/').reverse
    if trimmed.isEmpty && path.nonEmpty then None // a root
    else Some(trimmed.substring(trimmed.lastIndexOf('/') + 1))

  def resolveSibling(from: String, path: String): String =
    if valid(path).startsWith("/") then normalize(path)
    else
      val dir = valid(from).reverse.dropWhile(_ == '/').reverse
      dir.lastIndexOf('/') match
        case -1 => normalize(path)
        case 0 => normalize("/" + path)
        case i => normalize(dir.substring(0, i) + "/" + path)

  private def valid(path: String): String =
    if path.contains('\u0000') then throw IllegalArgumentException(s"invalid path: $path")
    path
