package hugin.core
package objtype

import hugin.obj.BaseType
import scala.collection.mutable

/** Subtyping, members, meets and joins of object types (reference: object/types). `Unknown` and `Err`
 *  are compatible with every type. A type with an abstract head (a functor's parameter type in the body)
 *  is a subtype only of itself and of what edges say; its meet with another type is `Unknown`, decided
 *  for each instance by the check of staged items. */
final class ObjTypes(val env: ObjEnv):
  private lazy val edgesFrom: Map[OTy, List[OTy]] = env.edges.groupBy(_._1).view.mapValues(_.map(_._2)).toMap

  private def edgesOf(t: OTy): List[OTy] = edgesFrom.getOrElse(t, Nil)

  /** The types directly above `t`. */
  private def ups(t: OTy): List[OTy] = t match
    case OTy.Fact(h, as) =>
      val above = env.relInfo(h, as).flatMap(_.result) match
        case Some(r) => List(r)
        case None => List(OTy.RelTop)
      above ++ edgesOf(t)
    case OTy.Con(h, as) =>
      env.kind(h, as) match
        case HeadKind.Open => OTy.RelTop :: edgesOf(t)
        case HeadKind.Refinement(b) => List(b)
        case _ => edgesOf(t)
    case _ => Nil

  private val subCache = mutable.HashMap.empty[(OTy, OTy), Boolean]

  /** `a ≤ b`: the least preorder generated by the declarations and edges. */
  def isSub(a: OTy, b: OTy): Boolean =
    if a == b || a.vague || b.vague || sameUpToUnknowns(a, b) then true
    else
      subCache.getOrElseUpdate(
        (a, b),
        (a, b) match
          case (OTy.Union(ms), _) => ms.forall(isSub(_, b))
          case (_, OTy.Union(ms)) if ms.exists(isSub(a, _)) => true
          case _ =>
            val seen = mutable.HashSet(a)
            val queue = mutable.Queue(a)
            var found = false
            while queue.nonEmpty && !found do
              for u <- ups(queue.dequeue()) if !found do
                if u == b then found = true
                else
                  b match
                    case OTy.Union(ms) if ms.contains(u) => found = true
                    case _ =>
                  if seen.add(u) then queue.enqueue(u)
            found
      )

  /** The same type, where an argument of one side is unknown. */
  private def sameUpToUnknowns(a: OTy, b: OTy): Boolean =
    def args(x: List[OTy], y: List[OTy]) = x.length == y.length && x.zip(y).forall((p, q) => p == q || p.vague || q.vague || sameUpToUnknowns(p, q))
    (a, b) match
      case (OTy.Con(h, as), OTy.Con(k, bs)) => h == k && args(as, bs)
      case (OTy.Fact(h, as), OTy.Fact(k, bs)) => h == k && args(as, bs)
      case _ => false

  def isRelLike(t: OTy): Boolean = t.vague || isSub(t, OTy.RelTop)

  /** Whether `t` mentions an abstract type (a functor's parameter type). */
  def isAbstract(t: OTy): Boolean = t match
    case OTy.Con(h, as) => env.kind(h, as) == HeadKind.Abstract
    case OTy.Union(ms) => ms.exists(isAbstract)
    case _ => false

  private val memCache = mutable.HashMap.empty[OTy, List[RelInfo]]

  /** The relations, constructors and structs whose facts are of type `t` (for `t ≤ rel`). */
  def members(t: OTy): List[RelInfo] = memCache.getOrElseUpdate(
    t,
    t match
      case OTy.Fact(h, as) => env.relInfo(h, as).toList
      case OTy.Union(ms) => ms.flatMap(members).distinct
      case _ => env.relationHeads.filter(r => isSub(r.fact, t))
  )

  /** A type is closed if it is a fact type or a union of closed types. */
  def isClosed(t: OTy): Boolean = t match
    case OTy.Fact(_, _) => true
    case OTy.Union(ms) => ms.forall(isClosed)
    case _ => false

  /** The base type under a base type or refinement. */
  def baseOf(t: OTy): Option[BaseType] =
    @annotation.tailrec
    def go(t: OTy, seen: Set[OTy]): Option[BaseType] = t match
      case OTy.Base(b) => Some(b)
      case c @ OTy.Con(h, as) if !seen(c) =>
        env.kind(h, as) match
          case HeadKind.Refinement(b) => go(b, seen + c)
          case _ => None
      case _ => None
    go(t, Set.empty)

  def isBaseLike(t: OTy): Boolean = baseOf(t).isDefined

  /** The meet `a ⊓ b`; `None` if no value has both types. */
  def meet(a: OTy, b: OTy): Option[OTy] =
    if a == OTy.Err || a == OTy.Unknown then Some(b)
    else if b == OTy.Err || b == OTy.Unknown then Some(a)
    else if isSub(a, b) then Some(a)
    else if isSub(b, a) then Some(b)
    else if a.vague || b.vague || isAbstract(a) || isAbstract(b) then Some(OTy.Unknown)
    else if isRelLike(a) && isRelLike(b) then
      val ms = members(a).map(_.fact).intersect(members(b).map(_.fact))
      Option.when(ms.nonEmpty)(OTy.union(ms))
    else None

  /** The labels common to all members of a closed type, with each member's column. */
  def commonLabel(t: OTy, l: String): Either[List[RelInfo], List[(RelInfo, Int, OTy)]] =
    val ms = members(t)
    val missing = ms.filter(_.labelIndex(l).isEmpty)
    if missing.nonEmpty then Left(missing)
    else Right(ms.map(r => (r, r.labelIndex(l).get, r.cols(r.labelIndex(l).get)._2)))

  /** The join of the column types of a common label. */
  def join(ts: List[OTy]): Option[OTy] =
    val d = ts.distinct
    if d.length == 1 then Some(d.head)
    else if d.forall(isRelLike) then Some(OTy.union(d))
    else None

  /** A type in surface notation. */
  def show(t: OTy): String = t match
    case OTy.Base(b) => b.show
    case OTy.Con(h, Nil) => env.name(h)
    case OTy.Con(h, as) => (env.name(h) :: as.map(showArg)).mkString(" ")
    case OTy.Fact(h, Nil) => env.name(h)
    case OTy.Fact(h, as) => (env.name(h) :: as.map(showArg)).mkString(" ")
    case OTy.RelTop => "rel"
    case OTy.Union(ms) => ms.map(show).mkString(" | ")
    case OTy.Unknown => "_"
    case OTy.Err => "<error>"

  private def showArg(t: OTy): String = t match
    case OTy.Con(_, _ :: _) | OTy.Fact(_, _ :: _) | OTy.Union(_) => s"(${show(t)})"
    case _ => show(t)
